import os
from decimal import Decimal
from unittest.mock import Mock, patch

import pytest
from dotenv import load_dotenv

from src.database_manager import DatabaseBase, DBManager


def test_DatabaseBase():
    with pytest.raises(TypeError):
        thing = DatabaseBase()


def test_DB_manager():
    """Для данной проверки у вас должна быть создана БД под названием test"""
    load_dotenv()
    test_DB = DBManager(
        dbname="test",
        user=os.getenv("DB_USER"),
        password=os.getenv("DB_PASSWORD"),
        host=os.getenv("DB_HOST"),
        port=os.getenv("DB_PORT"),
    )

    test_DB.create_tables()
    test_DB.add_information(
        [
            {
                "id": "92223870",
                "premium": False,
                "name": "Удаленный специалист службы поддержки (в Яндекс)",
                "department": None,
                "has_test": False,
                "response_letter_required": False,
                "area": {"id": "113", "name": "Россия", "url": "https://api.hh.ru/areas/113"},
                "salary": {"from": 40000, "to": 54000, "currency": None, "gross": True},
                "type": {"id": "open", "name": "Открытая"},
                "address": None,
                "response_url": None,
                "sort_point_distance": None,
                "published_at": "2024-01-25T17:39:01+0300",
                "created_at": "2024-01-25T17:39:01+0300",
                "archived": False,
                "apply_alternate_url": "https://hh.ru/applicant/vacancy_response?vacancyId=92223870",
                "show_logo_in_search": None,
                "insider_interview": None,
                "url": "https://api.hh.ru/vacancies/92223870?host=hh.ru",
                "alternate_url": "https://hh.ru/vacancy/92223870",
                "relations": [],
                "employer": {
                    "id": "9498120",
                    "name": "Яндекс Команда для бизнеса",
                    "url": "https://api.hh.ru/employers/9498120",
                    "alternate_url": "https://hh.ru/employer/9498120",
                    "logo_urls": {
                        "original": "https://hhcdn.ru/employer-logo-original/1121425.jpg",
                        "90": "https://hhcdn.ru/employer-logo/6106293.jpeg",
                        "240": "https://hhcdn.ru/employer-logo/6106294.jpeg",
                    },
                    "vacancies_url": "https://api.hh.ru/vacancies?employer_id=9498120",
                    "accredited_it_employer": False,
                    "trusted": True,
                },
                "snippet": {
                    "requirement": "Способен работать в команде. Способен принимать решения самостоятельно. Готов учиться и узнавать новое. Опыт работы в колл-центре или службе...",
                    "responsibility": "Работать с клиентами или партнерами для решения разнообразных ситуаций. Совершать звонки по их обращениям и давать письменные ответы. ",
                },
                "contacts": None,
                "schedule": {"id": "remote", "name": "Удаленная работа"},
                "working_days": [],
                "working_time_intervals": [],
                "working_time_modes": [{"id": "start_after_sixteen", "name": "Можно начинать работать после 16:00"}],
                "accept_temporary": False,
                "professional_roles": [{"id": "40", "name": "Другое"}],
                "accept_incomplete_resumes": True,
                "experience": {"id": "noExperience", "name": "Нет опыта"},
                "employment": {"id": "full", "name": "Полная занятость"},
                "adv_response_url": None,
                "is_adv_vacancy": False,
                "adv_context": None,
            },
            {
                "id": "92223756",
                "premium": False,
                "name": "Удаленный диспетчер чатов (в Яндекс)",
                "department": None,
                "has_test": False,
                "response_letter_required": False,
                "area": {"id": "113", "name": "Россия", "url": "https://api.hh.ru/areas/113"},
                "salary": {"from": None, "to": 44000, "currency": "RUR", "gross": True},
                "type": {"id": "open", "name": "Открытая"},
                "address": None,
                "response_url": None,
                "sort_point_distance": None,
                "published_at": "2024-01-25T17:37:04+0300",
                "created_at": "2024-01-25T17:37:04+0300",
                "archived": False,
                "apply_alternate_url": "https://hh.ru/applicant/vacancy_response?vacancyId=92223756",
                "show_logo_in_search": None,
                "insider_interview": None,
                "url": "https://api.hh.ru/vacancies/92223756?host=hh.ru",
                "alternate_url": "https://hh.ru/vacancy/92223756",
                "relations": [],
                "employer": {
                    "id": "9498120",
                    "name": "Яндекс Команда для бизнеса",
                    "url": "https://api.hh.ru/employers/9498120",
                    "alternate_url": "https://hh.ru/employer/9498120",
                    "logo_urls": {
                        "original": "https://hhcdn.ru/employer-logo-original/1121425.jpg",
                        "90": "https://hhcdn.ru/employer-logo/6106293.jpeg",
                        "240": "https://hhcdn.ru/employer-logo/6106294.jpeg",
                    },
                    "vacancies_url": "https://api.hh.ru/vacancies?employer_id=9498120",
                    "accredited_it_employer": False,
                    "trusted": True,
                },
                "snippet": {
                    "requirement": "Способен работать в команде. Способен принимать решения самостоятельно. Готов учиться и узнавать новое. Опыт работы в колл-центре или службе...",
                    "responsibility": "Работать с клиентами или партнерами для решения разнообразных ситуаций. Совершать звонки по их обращениям и давать письменные ответы. ",
                },
                "contacts": None,
                "schedule": {"id": "remote", "name": "Удаленная работа"},
                "working_days": [],
                "working_time_intervals": [],
                "working_time_modes": [{"id": "start_after_sixteen", "name": "Можно начинать работать после 16:00"}],
                "accept_temporary": False,
                "professional_roles": [{"id": "40", "name": "Другое"}],
                "accept_incomplete_resumes": True,
                "experience": {"id": "noExperience", "name": "Нет опыта"},
                "employment": {"id": "full", "name": "Полная занятость"},
                "adv_response_url": None,
                "is_adv_vacancy": False,
                "adv_context": None,
            },
            {
                "id": "92223870",
                "premium": False,
                "name": "Удаленный специалист службы поддержки (в Яндекс)",
                "department": None,
                "has_test": False,
                "response_letter_required": False,
                "area": {"id": "113", "name": "Россия", "url": "https://api.hh.ru/areas/113"},
                "salary": {"from": 30000, "to": None, "currency": "RUR", "gross": True},
                "type": {"id": "open", "name": "Открытая"},
                "address": None,
                "response_url": None,
                "sort_point_distance": None,
                "published_at": "2024-01-25T17:39:01+0300",
                "created_at": "2024-01-25T17:39:01+0300",
                "archived": False,
                "apply_alternate_url": "https://hh.ru/applicant/vacancy_response?vacancyId=92223870",
                "show_logo_in_search": None,
                "insider_interview": None,
                "url": "https://api.hh.ru/vacancies/92223870?host=hh.ru",
                "alternate_url": "https://hh.ru/vacancy/92223870",
                "relations": [],
                "employer": {
                    "id": "9498120",
                    "name": "Яндекс Команда для бизнеса",
                    "url": "https://api.hh.ru/employers/9498120",
                    "alternate_url": "https://hh.ru/employer/9498120",
                    "logo_urls": {
                        "original": "https://hhcdn.ru/employer-logo-original/1121425.jpg",
                        "90": "https://hhcdn.ru/employer-logo/6106293.jpeg",
                        "240": "https://hhcdn.ru/employer-logo/6106294.jpeg",
                    },
                    "vacancies_url": "https://api.hh.ru/vacancies?employer_id=9498120",
                    "accredited_it_employer": False,
                    "trusted": True,
                },
                "snippet": {
                    "requirement": "Способен работать в команде. Способен принимать решения самостоятельно. Готов учиться и узнавать новое. Опыт работы в колл-центре или службе...",
                    "responsibility": "Работать с клиентами или партнерами для решения разнообразных ситуаций. Совершать звонки по их обращениям и давать письменные ответы. ",
                },
                "contacts": None,
                "schedule": {"id": "remote", "name": "Удаленная работа"},
                "working_days": [],
                "working_time_intervals": [],
                "working_time_modes": [{"id": "start_after_sixteen", "name": "Можно начинать работать после 16:00"}],
                "accept_temporary": False,
                "professional_roles": [{"id": "40", "name": "Другое"}],
                "accept_incomplete_resumes": True,
                "experience": {"id": "noExperience", "name": "Нет опыта"},
                "employment": {"id": "full", "name": "Полная занятость"},
                "adv_response_url": None,
                "is_adv_vacancy": False,
                "adv_context": None,
            },
            {
                "id": "92223873",
                "premium": False,
                "name": "Удаленный специалист службы поддержки (в Яндекс)",
                "department": None,
                "has_test": False,
                "response_letter_required": False,
                "area": {"id": "113", "name": "Россия", "url": "https://api.hh.ru/areas/113"},
                "salary": {"from": None, "to": None, "currency": "RUR", "gross": True},
                "type": {"id": "open", "name": "Открытая"},
                "address": None,
                "response_url": None,
                "sort_point_distance": None,
                "published_at": "2024-01-25T17:39:01+0300",
                "created_at": "2024-01-25T17:39:01+0300",
                "archived": False,
                "apply_alternate_url": "https://hh.ru/applicant/vacancy_response?vacancyId=92223870",
                "show_logo_in_search": None,
                "insider_interview": None,
                "url": "https://api.hh.ru/vacancies/92223870?host=hh.ru",
                "alternate_url": "https://hh.ru/vacancy/92223870",
                "relations": [],
                "employer": {
                    "id": "9498120",
                    "name": "Яндекс Команда для бизнеса",
                    "url": "https://api.hh.ru/employers/9498120",
                    "alternate_url": "https://hh.ru/employer/9498120",
                    "logo_urls": {
                        "original": "https://hhcdn.ru/employer-logo-original/1121425.jpg",
                        "90": "https://hhcdn.ru/employer-logo/6106293.jpeg",
                        "240": "https://hhcdn.ru/employer-logo/6106294.jpeg",
                    },
                    "vacancies_url": "https://api.hh.ru/vacancies?employer_id=9498120",
                    "accredited_it_employer": False,
                    "trusted": True,
                },
                "snippet": {
                    "requirement": "Способен работать в команде. Способен принимать решения самостоятельно. Готов учиться и узнавать новое. Опыт работы в колл-центре или службе...",
                    "responsibility": "Работать с клиентами или партнерами для решения разнообразных ситуаций. Совершать звонки по их обращениям и давать письменные ответы. ",
                },
                "contacts": None,
                "schedule": {"id": "remote", "name": "Удаленная работа"},
                "working_days": [],
                "working_time_intervals": [],
                "working_time_modes": [{"id": "start_after_sixteen", "name": "Можно начинать работать после 16:00"}],
                "accept_temporary": False,
                "professional_roles": [{"id": "40", "name": "Другое"}],
                "accept_incomplete_resumes": True,
                "experience": {"id": "noExperience", "name": "Нет опыта"},
                "employment": {"id": "full", "name": "Полная занятость"},
                "adv_response_url": None,
                "is_adv_vacancy": False,
                "adv_context": None,
            },
            {
                "id": "92223874",
                "premium": False,
                "name": "Удаленный специалист службы поддержки (в Вайлдберриз)",
                "department": None,
                "has_test": False,
                "response_letter_required": False,
                "area": {"id": "113", "name": "Россия", "url": "https://api.hh.ru/areas/113"},
                "salary": {"from": None, "to": None, "currency": None, "gross": True},
                "type": {"id": "open", "name": "Открытая"},
                "address": None,
                "response_url": None,
                "sort_point_distance": None,
                "published_at": "2024-01-25T17:39:01+0300",
                "created_at": "2024-01-25T17:39:01+0300",
                "archived": False,
                "apply_alternate_url": "https://hh.ru/applicant/vacancy_response?vacancyId=92223870",
                "show_logo_in_search": None,
                "insider_interview": None,
                "url": "https://api.hh.ru/vacancies/92223870?host=hh.ru",
                "alternate_url": "https://hh.ru/vacancy/92223870",
                "relations": [],
                "employer": {
                    "id": "9498121",
                    "name": "Вайлдберриз Команда для бизнеса",
                    "url": "https://api.hh.ru/employers/9498120",
                    "alternate_url": "https://hh.ru/employer/9498120",
                    "logo_urls": {
                        "original": "https://hhcdn.ru/employer-logo-original/1121425.jpg",
                        "90": "https://hhcdn.ru/employer-logo/6106293.jpeg",
                        "240": "https://hhcdn.ru/employer-logo/6106294.jpeg",
                    },
                    "vacancies_url": "https://api.hh.ru/vacancies?employer_id=9498120",
                    "accredited_it_employer": False,
                    "trusted": True,
                },
                "snippet": {
                    "requirement": "Способен работать в команде. Способен принимать решения самостоятельно. Готов учиться и узнавать новое. Опыт работы в колл-центре или службе...",
                    "responsibility": "Работать с клиентами или партнерами для решения разнообразных ситуаций. Совершать звонки по их обращениям и давать письменные ответы. ",
                },
                "contacts": None,
                "schedule": {"id": "remote", "name": "Удаленная работа"},
                "working_days": [],
                "working_time_intervals": [],
                "working_time_modes": [{"id": "start_after_sixteen", "name": "Можно начинать работать после 16:00"}],
                "accept_temporary": False,
                "professional_roles": [{"id": "40", "name": "Другое"}],
                "accept_incomplete_resumes": True,
                "experience": {"id": "noExperience", "name": "Нет опыта"},
                "employment": {"id": "full", "name": "Полная занятость"},
                "adv_response_url": None,
                "is_adv_vacancy": False,
                "adv_context": None,
            },
        ]
    )
    assert (
        test_DB.get_all_vacancies()
        == [
            (
                "Яндекс Команда для бизнеса",
                "Удаленный специалист службы поддержки (в Яндекс)",
                Decimal("47000"),
                None,
                "https://hh.ru/vacancy/92223870",
            ),
            (
                "Яндекс Команда для бизнеса",
                "Удаленный диспетчер чатов (в Яндекс)",
                Decimal("44000"),
                "RUR",
                "https://hh.ru/vacancy/92223756",
            ),
            (
                "Яндекс Команда для бизнеса",
                "Удаленный специалист службы поддержки (в Яндекс)",
                Decimal("0"),
                "RUR",
                "https://hh.ru/vacancy/92223870",
            ),
            (
                "Вайлдберриз Команда для бизнеса",
                "Удаленный специалист службы поддержки (в Вайлдберриз)",
                Decimal("0"),
                None,
                "https://hh.ru/vacancy/92223870",
            ),
        ]
        != [
            (
                "Яндекс Команда для бизнеса",
                "Удаленный специалист службы поддержки (в Яндекс)",
                Decimal("47000"),
                None,
                "https://hh.ru/vacancy/92223870",
            ),
            (
                "Яндекс Команда для бизнеса",
                "Удаленный диспетчер чатов (в Яндекс)",
                Decimal("44000"),
                "RUR",
                "https://hh.ru/vacancy/92223756",
            ),
        ]
    )
    assert test_DB.get_companies_and_vacancies_count() == [
        ("Яндекс Команда для бизнеса", 3),
        ("Вайлдберриз Команда для бизнеса", 1),
    ]
    assert test_DB.get_avg_salary() == [
        ("Яндекс Команда для бизнеса", "Удаленный специалист службы поддержки (в Яндекс)", Decimal("47000"), None),
        ("Яндекс Команда для бизнеса", "Удаленный диспетчер чатов (в Яндекс)", Decimal("44000"), "RUR"),
        ("Яндекс Команда для бизнеса", "Удаленный специалист службы поддержки (в Яндекс)", Decimal("0"), "RUR"),
        (
            "Вайлдберриз Команда для бизнеса",
            "Удаленный специалист службы поддержки (в Вайлдберриз)",
            Decimal("0"),
            None,
        ),
    ]
    assert test_DB.get_vacancies_with_higher_salary() == [
        ("Яндекс Команда для бизнеса", "Удаленный диспетчер чатов (в Яндекс)", Decimal("44000"), "RUR")
    ]
    assert test_DB.get_vacancies_with_keyword("Яндекс") == [
        (
            "Яндекс Команда для бизнеса",
            "Удаленный специалист службы поддержки (в Яндекс)",
            Decimal("47000"),
            None,
            "https://hh.ru/vacancy/92223870",
        ),
        (
            "Яндекс Команда для бизнеса",
            "Удаленный диспетчер чатов (в Яндекс)",
            Decimal("44000"),
            "RUR",
            "https://hh.ru/vacancy/92223756",
        ),
        (
            "Яндекс Команда для бизнеса",
            "Удаленный специалист службы поддержки (в Яндекс)",
            Decimal("0"),
            "RUR",
            "https://hh.ru/vacancy/92223870",
        ),
    ]
    test_DB.cur.execute("""DROP TABLE schema_1.vacancies""")
    test_DB.cur.execute("""DROP TABLE schema_1.employer""")
    test_DB.cur.execute("""DROP SCHEMA schema_1""")
    test_DB.conn.commit()
    test_DB.close()
